# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/pkhunter

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	MARLGame-Android-DebugGame  \
	MARLGame-Android-Development  \
	MARLGame-Android-Shipping  \
	MARLGame-Linux-DebugGame  \
	MARLGame-Linux-Development  \
	MARLGame-Linux-Shipping  \
	MARLGame-LinuxArm64-DebugGame  \
	MARLGame-LinuxArm64-Development  \
	MARLGame-LinuxArm64-Shipping  \
	MARLGame \
	MARLGameEditor-Linux-DebugGame  \
	MARLGameEditor-Linux-Development  \
	MARLGameEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MARLGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MARLGameEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

MARLGame-Android-DebugGame:
	 $(BUILD) MARLGame Android DebugGame  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-Android-Development:
	 $(BUILD) MARLGame Android Development  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-Android-Shipping:
	 $(BUILD) MARLGame Android Shipping  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-Linux-DebugGame:
	 $(BUILD) MARLGame Linux DebugGame  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-Linux-Development:
	 $(BUILD) MARLGame Linux Development  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-Linux-Shipping:
	 $(BUILD) MARLGame Linux Shipping  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-LinuxArm64-DebugGame:
	 $(BUILD) MARLGame LinuxArm64 DebugGame  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-LinuxArm64-Development:
	 $(BUILD) MARLGame LinuxArm64 Development  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame-LinuxArm64-Shipping:
	 $(BUILD) MARLGame LinuxArm64 Shipping  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGame: MARLGame-Linux-Development

MARLGameEditor-Linux-DebugGame:
	 $(BUILD) MARLGameEditor Linux DebugGame  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGameEditor-Linux-Development:
	 $(BUILD) MARLGameEditor Linux Development  -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" $(ARGS)

MARLGameEditor: MARLGameEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/pkhunter/Repositories/MARLGame/MARLGame.uproject" -Game 

.PHONY: $(TARGETS)
